In [1]:
import GetOldTweets3 as got
import time
from datetime import datetime, date, timedelta
import pandas as pd
import numpy as np

In [20]:
def DownloadTweets(SinceDate, UntilDate, query, sleep=900, maxtweet=0) :
    #create a list of day numbers
    since = datetime.strptime(SinceDate, '%Y-%m-%d')
    days = list(range(0, (datetime.strptime(UntilDate, '%Y-%m-%d') - datetime.strptime(SinceDate, '%Y-%m-%d')).days+1))
    tweets = []

    for day in days:
        init = got.manager.TweetCriteria().setQuerySearch(query).setSince((since + timedelta(days=day)).strftime('%Y-%m-%d')).setUntil((since+ timedelta(days=day+1)).strftime('%Y-%m-%d')).setMaxTweets(maxtweet)
        get = got.manager.TweetManager.getTweets(init)
        tweets.append([[
        # tweet.id,
        # tweet.date, this could allow me to loop through?
        tweet.text
        ] for tweet in get])

        print("day", day+1, "of", len(days), "completed")
#         print("sleeping for", sleep, "seconds")
        time.sleep(sleep)
    #flatten list
    tweets = [tweet for sublist in tweets for tweet in sublist]

    # [print(n[0], sep='\n') for n in tweets]
    hmm = [n[0] for n in tweets]

    
    df = pd.DataFrame({'tweets': hmm, 'query': query})
    
    
    
    return df


#%%
since = "2020-01-01"
until = "2020-09-02"

tweets = DownloadTweets(since, until, query=' my power went out ', maxtweet=9_999, sleep=10)

day 1 of 246 completed
day 2 of 246 completed
day 3 of 246 completed
day 4 of 246 completed
day 5 of 246 completed
day 6 of 246 completed
day 7 of 246 completed
day 8 of 246 completed
day 9 of 246 completed
day 10 of 246 completed
day 11 of 246 completed
day 12 of 246 completed
day 13 of 246 completed
day 14 of 246 completed
day 15 of 246 completed
day 16 of 246 completed
day 17 of 246 completed
day 18 of 246 completed
day 19 of 246 completed
day 20 of 246 completed
day 21 of 246 completed
day 22 of 246 completed
day 23 of 246 completed
day 24 of 246 completed
day 25 of 246 completed
day 26 of 246 completed
day 27 of 246 completed
day 28 of 246 completed
day 29 of 246 completed
day 30 of 246 completed
day 31 of 246 completed
day 32 of 246 completed
day 33 of 246 completed
day 34 of 246 completed
day 35 of 246 completed
day 36 of 246 completed
day 37 of 246 completed
day 38 of 246 completed
day 39 of 246 completed
day 40 of 246 completed
day 41 of 246 completed
day 42 of 246 completed
day 43 of 246 completed
day 44 of 246 completed
day 45 of 246 completed
day 46 of 246 completed
day 47 of 246 completed
day 48 of 246 completed
day 49 of 246 completed
day 50 of 246 completed
day 51 of 246 completed
day 52 of 246 completed
day 53 of 246 completed
day 54 of 246 completed
day 55 of 246 completed
day 56 of 246 completed
day 57 of 246 completed
day 58 of 246 completed
day 59 of 246 completed
day 60 of 246 completed
day 61 of 246 completed
day 62 of 246 completed
day 63 of 246 completed
day 64 of 246 completed
day 65 of 246 completed
day 66 of 246 completed
day 67 of 246 completed
day 68 of 246 completed
day 69 of 246 completed
day 70 of 246 completed
day 71 of 246 completed
day 72 of 246 completed
day 73 of 246 completed
day 74 of 246 completed
day 75 of 246 completed
day 76 of 246 completed
day 77 of 246 completed
day 78 of 246 completed
day 79 of 246 completed
day 80 of 246 completed
day 81 of 246 completed
day 82 of 246 completed
day 83 of 246 completed
day 84 of 246 completed
day 85 of 246 completed
day 86 of 246 completed
day 87 of 246 completed
day 88 of 246 completed
day 89 of 246 completed
day 90 of 246 completed
day 91 of 246 completed
day 92 of 246 completed
day 93 of 246 completed
day 94 of 246 completed
day 95 of 246 completed
day 96 of 246 completed
day 97 of 246 completed
day 98 of 246 completed
day 99 of 246 completed
day 100 of 246 completed
day 101 of 246 completed
day 102 of 246 completed
day 103 of 246 completed
day 104 of 246 completed
day 105 of 246 completed
day 106 of 246 completed
day 107 of 246 completed
day 108 of 246 completed
day 109 of 246 completed
day 110 of 246 completed
day 111 of 246 completed
day 112 of 246 completed
day 113 of 246 completed
day 114 of 246 completed
day 115 of 246 completed
day 116 of 246 completed
day 117 of 246 completed
day 118 of 246 completed
day 119 of 246 completed
day 120 of 246 completed
day 121 of 246 completed
day 122 of 246 completed
day 123 of 246 completed
day 124 of 246 completed
day 125 of 246 completed
day 126 of 246 completed
day 127 of 246 completed
day 128 of 246 completed
day 129 of 246 completed
day 130 of 246 completed
day 131 of 246 completed
day 132 of 246 completed
day 133 of 246 completed
day 134 of 246 completed
day 135 of 246 completed
day 136 of 246 completed
day 137 of 246 completed
day 138 of 246 completed
day 139 of 246 completed
day 140 of 246 completed
day 141 of 246 completed
day 142 of 246 completed
day 143 of 246 completed
day 144 of 246 completed
day 145 of 246 completed
day 146 of 246 completed
day 147 of 246 completed
day 148 of 246 completed
day 149 of 246 completed
day 150 of 246 completed
day 151 of 246 completed
day 152 of 246 completed
day 153 of 246 completed
day 154 of 246 completed
day 155 of 246 completed
day 156 of 246 completed
day 157 of 246 completed
day 158 of 246 completed
day 159 of 246 completed
day 160 of 246 completed
day 161 of 246 completed
day 162 of 246 completed
day 163 of 246 completed
day 164 of 246 completed
day 165 of 246 completed
day 166 of 246 completed
day 167 of 246 completed
day 168 of 246 completed
day 169 of 246 completed
day 170 of 246 completed
day 171 of 246 completed
day 172 of 246 completed
day 173 of 246 completed
day 174 of 246 completed
day 175 of 246 completed
day 176 of 246 completed
day 177 of 246 completed
day 178 of 246 completed
day 179 of 246 completed
day 180 of 246 completed
day 181 of 246 completed
day 182 of 246 completed
day 183 of 246 completed
day 184 of 246 completed
day 185 of 246 completed
day 186 of 246 completed
day 187 of 246 completed
day 188 of 246 completed
day 189 of 246 completed
day 190 of 246 completed
day 191 of 246 completed
day 192 of 246 completed
day 193 of 246 completed
day 194 of 246 completed
day 195 of 246 completed
day 196 of 246 completed
day 197 of 246 completed
day 198 of 246 completed
day 199 of 246 completed
day 200 of 246 completed
day 201 of 246 completed
day 202 of 246 completed
day 203 of 246 completed
day 204 of 246 completed
day 205 of 246 completed
day 206 of 246 completed
day 207 of 246 completed
day 208 of 246 completed
day 209 of 246 completed
day 210 of 246 completed
day 211 of 246 completed
day 212 of 246 completed
day 213 of 246 completed
day 214 of 246 completed
day 215 of 246 completed
day 216 of 246 completed
day 217 of 246 completed
day 218 of 246 completed
day 219 of 246 completed
day 220 of 246 completed
day 221 of 246 completed
day 222 of 246 completed
day 223 of 246 completed
day 224 of 246 completed
day 225 of 246 completed
day 226 of 246 completed
day 227 of 246 completed
day 228 of 246 completed
day 229 of 246 completed
day 230 of 246 completed
day 231 of 246 completed
day 232 of 246 completed
day 233 of 246 completed
day 234 of 246 completed
day 235 of 246 completed
day 236 of 246 completed
day 237 of 246 completed
day 238 of 246 completed
day 239 of 246 completed
day 240 of 246 completed
day 241 of 246 completed
day 242 of 246 completed
day 243 of 246 completed
day 244 of 246 completed
day 245 of 246 completed
day 246 of 246 completed

In [22]:
tweets.to_csv('tweets.csv',index=False)

In [23]:
tweets

                                                  tweets                query
0      Thank you, I just found out my Dads power is b...   my power went out
1      My power went out during stream and I'm just s...   my power went out
2      nah not a bushfire my power just went out for ...   my power went out
3      In 2005 I realized my power to manifest my rea...   my power went out
4      I don’t have a car, and I’m on full disability...   my power went out
...                                                  ...                  ...
55392                   My power went out mid stream lol   my power went out
55393  bruh. my power and wifi went out how tf am i g...   my power went out
55394  power steering on my car went out when my dad ...   my power went out
55395  I couldn't see anything and the wind was blowi...   my power went out
55396  AHHH.... was on my best run of sunless skies w...   my power went out

[55397 rows x 2 columns]